id: A6E0A52EA
title: f5CBB
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:35:19.966387
  last_modified_at: 2022-05-27 19:35:19.966391
